/*
 * MFActionConfirm.h
 *
 *  Created on: 15.09.2020
 *      Author: michl
 */

#ifndef MFSCENEACTIONS_MFACTIONCONFIRM_H_
#define MFSCENEACTIONS_MFACTIONCONFIRM_H_

#include "MFBaseActionTask.h"

/**
 * This action confirms the execution of another action with action related data.
 * The action related data will be generated by the action which shall be confirmed.
 * Datagram:
 * ConfirmActionTaskIndex
 * ConfirmDataSize
 * ConfirmData
 *
 */
class MFActionConfirm: public MFBaseActionTask {
private:
  MFStructurableData*
  mp_confirmData;
public:
  MFActionConfirm();
  virtual ~MFActionConfirm();
  void setConfirmData(MFStructurableData* pConfirmData){
    mp_confirmData=pConfirmData;
  }
};

#endif /* MFSCENEACTIONS_MFACTIONCONFIRM_H_ */
