/*
 * MFInputTaskManager.h
 *
 *  Created on: 25.05.2020
 *      Author: michl
 */

#ifndef MFENGINEMODULES_MFINPUTMODULES_MFINPUTTASKS_MFINPUTTASKMANAGER_H_
#define MFENGINEMODULES_MFINPUTMODULES_MFINPUTTASKS_MFINPUTTASKMANAGER_H_

#include <MFTasks/MFTaskManager.h>

class MFInputTaskManager: public MFTaskManager {
};

#endif /* MFENGINEMODULES_MFINPUTMODULES_MFINPUTTASKS_MFINPUTTASKMANAGER_H_ */
